version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle install --retry=3

test_script:
  - bundle exec rake

build: off
